# Variables
@baseUrl = http://localhost:3333
@token = {{auth.response.body.$.token}}

# @name auth
POST {{baseUrl}}/auth
Content-Type: application/json

{
  "email": "user.admin@servidor.uepb.edu.br",
  "password": "123456"
}

###

# @name createMasterUser
POST {{baseUrl}}/users/master
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Master User",
  "email": "user.master@email.com",
  "password": "123456"
}

###

# @name createAdminUser
POST {{baseUrl}}/users/admin
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Admin User",
  "email": "user.admin@servidor.uepb.edu.br",
  "password": "123456",
  "cpf": "12345678900",
  "contactPhone": "83912345678",
  "institution": "Universidade Estadual da Paraíba"
}

###

# @name createApplicatorUser
POST {{baseUrl}}/users/applicator
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Applicator User",
  "email": "user.applicator@servidor.uepb.edu.br",
  "password": "123456",
  "cpf": "12345678900",
  "contactPhone": "83912345678",
  "academicBackground": "Bacharel em Ciência da Computação"
}