# Variables
@baseUrl = http://localhost:3333
@token = {{auth.response.body.$.token}}
@sessionId = {{createSession.response.body.$.sessionId}}

# ----- Auth routes -----

# @name auth
POST {{baseUrl}}/auth
Content-Type: application/json

{
  "email": "user.admin@servidor.uepb.edu.br",
  "password": "123456"
}

###

# @name generateOtpCode
POST {{baseUrl}}/auth/otp-code/generate
Content-Type: application/json

{
  "email": "joao.lima.sousa@aluno.uepb.edu.br"
}

###

# @name verifyOtpCode
POST {{baseUrl}}/auth/otp-code/verify
Content-Type: application/json

{
  "email": "joao.lima.sousa@aluno.uepb.edu.br",
  "code": "797217"
}

###

# @name resetPassword
POST {{baseUrl}}/auth/reset-password
Content-Type: application/json

{
  "email": "joao.lima.sousa@aluno.uepb.edu.br",
  "password": "654321"
}

###

# @name getProfile
GET {{baseUrl}}/users/profile
Authorization: Bearer {{token}}

###

# ----- Users routes -----

# @name getInactiveUsers
GET {{baseUrl}}/users/inactive
Authorization: Bearer {{token}}

###

# @name createAdminUser
POST {{baseUrl}}/users/admin
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Admin User",
  "email": "user.admin@servidor.uepb.edu.br",
  "password": "123456",
  "cpf": "12345678900",
  "contactPhone": "83912345678",
  "institution": "Universidade Estadual da Paraíba"
}

###

# @name createApplicatorUser
POST {{baseUrl}}/users/applicator
Content-Type: application/json

{
  "name": "Applicator User",
  "email": "user.applicator@servidor.uepb.edu.br",
  "password": "123456",
  "cpf": "12345678900",
  "contactPhone": "83912345678",
  "institution": "Universidade Estadual da Paraíba"
}

###

# @name updateApplicatorUser
PATCH {{baseUrl}}/users/applicator
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Applicator User Updated",
  "contactPhone": "83912345678",
  "institution": "Universidade Estadual da Paraíba"
}

###

# Students routes

# @name createStudent
POST {{baseUrl}}/students
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Student 3",
  "birthDate": "2025-10-10",
  "gender": "male",
  "grade": "Portugês"
}

###

# ----- Sessions routes -----

# @name createSession
POST {{baseUrl}}/sessions
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "studentId": "267ed68f-2915-4d7a-92d6-1be956965c5b",
  "durationInSeconds": 120,
  "countQuestion": 5,
  "score": 4,
  "percentage": 80,
  "skill": "Skill A",
  "thetaFinal": 3,
  "thetaError": 2,
  "startTime": "2025-05-22 15:00:00",
  "endTime": "2025-05-22 15:02:00"
}

###

# @name createSessionItem
POST {{baseUrl}}/sessions/{{sessionId}}/items
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "correctAnswer": "A",
  "difficulty": 9,
  "discrimination": 3,
  "guessing": 2,
  "information": 2,
  "isCorrect": true,
  "itemIndex": 1,
  "playerAnswer": "A",
  "probability": 4,
  "questionNumber": 2,
  "stimulusName": "stimulus",
  "skill": "Skill A",
  "responseTimeInSeconds": 30,
  "thetaAfter": 3,
  "thetaBefore": 7,
  "thetaError": 2
}

###

# ----- Contacts routes -----

# @name createContact
POST {{baseUrl}}/contacts
Content-Type: application/json

{
  "name": "Ghost User",
  "email": "ghost.user@email.com",
  "subject": "Inserir minha instituição no sistema",
  "message": "Quero utilizar o sistema na minha instituição"
}

###

# @name closeContactById
PATCH {{baseUrl}}/contacts/b75b24c6-eb52-4538-bceb-1be19ab41415/close
Authorization: Bearer {{token}}

###

# @name getContacts
GET {{baseUrl}}/contacts
Authorization: Bearer {{token}}

###

# @name getContactById
GET {{baseUrl}}/contacts/b75b24c6-eb52-4538-bceb-1be19ab41415
Authorization: Bearer {{token}}