# Variables
@baseUrl = http://localhost:3333
@token = {{auth.response.body.$.token}}

# ----- Auth routes -----

# @name auth
POST {{baseUrl}}/auth
Content-Type: application/json

{
  "email": "joao.lima.sousa@aluno.uepb.edu.br",
  "password": "654321"
}

###

# @name generateOtpCode
POST {{baseUrl}}/auth/otp-code/generate
Content-Type: application/json

{
  "email": "joao.lima.sousa@aluno.uepb.edu.br"
}

###

# @name verifyOtpCode
POST {{baseUrl}}/auth/otp-code/verify
Content-Type: application/json

{
  "email": "joao.lima.sousa@aluno.uepb.edu.br",
  "code": "991125"
}

###

# @name resetPassword
POST {{baseUrl}}/auth/reset-password
Content-Type: application/json

{
  "email": "joao.lima.sousa@aluno.uepb.edu.br",
  "password": "654321"
}

###

# @name getProfile
GET {{baseUrl}}/users/profile
Authorization: Bearer {{token}}

###

# @name createMasterUser
POST {{baseUrl}}/users/master
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Master User",
  "email": "user.master@email.com",
  "password": "123456"
}

###

# ----- Users routes -----

# @name createAdminUser
POST {{baseUrl}}/users/admin
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Admin User",
  "email": "user.admin@servidor.uepb.edu.br",
  "password": "123456",
  "cpf": "12345678900",
  "contactPhone": "83912345678",
  "institution": "Universidade Estadual da Paraíba"
}

###

# @name createApplicatorUser
POST {{baseUrl}}/users/applicator
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "João Vitor de Lima Sousa",
  "email": "joao.lima.sousa@aluno.uepb.edu.br",
  "password": "123456",
  "cpf": "12345678900",
  "contactPhone": "83912345678",
  "academicBackground": "Bacharel em Ciência da Computação"
}

###

# @name updateApplicatorUser
PATCH {{baseUrl}}/users/applicator
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Applicator User Updated",
  "contactPhone": "83912345678",
  "academicBackground": "Bacharel em Ciência da Computação"
}

###

# ----- Contacts routes -----

# @name createContact
POST {{baseUrl}}/contacts
Content-Type: application/json

{
  "name": "Ghost User",
  "email": "ghost.user@email.com",
  "subject": "Inserir minha instituição no sistema",
  "message": "Quero utilizar o sistema na minha instituição"
}

###

# @name closeContactById
PATCH {{baseUrl}}/contacts/b75b24c6-eb52-4538-bceb-1be19ab41415/close
Authorization: Bearer {{token}}

###

# @name getContacts
GET {{baseUrl}}/contacts
Authorization: Bearer {{token}}

###

# @name getContactById
GET {{baseUrl}}/contacts/b75b24c6-eb52-4538-bceb-1be19ab41415
Authorization: Bearer {{token}}